version: '3'
services:
  webserver:
    image: php:apache
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
      - ./vendor:/var/www/html/vendor
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "composer install && apache2-foreground"
    env_file:
      - .env
    expose:
      - 9000

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    command: --lower_case_table_names=0
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database:db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}